### PR TITLE
Ignore the exit code of `modprobe` always

### LINKED ISSUE #466: No network inside containers launched inside dind on CentOS 7 host
We're seeing issues where dind images after `docker:24.0.6-dind` have issues with networking inside the inner containers.  The following logs are using the `docker@sha256:8f9c4d8cdaa2f87b5269d4d6759711c843c37e34a02b8bb45653e5b8f4e2f0a2` image, which I believe should have the updates from https://github.com/docker-library/docker/issues/463  (please let me know if ti doesn't).

I can reproduce our issues by launching dind with `docker run --rm -ti --privileged --name docker -e DOCKER_TLS_CERTDIR= -p 2375:2375 docker@sha256:8f9c4d8cdaa2f87b5269d4d6759711c843c37e34a02b8bb45653e5b8f4e2f0a2`

```
INFO[2023-12-15T21:40:41.852525583Z] Starting up
WARN[2023-12-15T21:40:41.853150377Z] Binding to IP address without --tlsverify is insecure and gives root access on this machine to everyone who has access to your network.  host="tcp://0.0.0.0:2375"
WARN[2023-12-15T21:40:41.853168377Z] Binding to an IP address, even on localhost, can also give access to scripts run in a browser. Be safe out there!  host="tcp://0.0.0.0:2375"
WARN[2023-12-15T21:40:42.853328719Z] Binding to an IP address without --tlsverify is deprecated. Startup is intentionally being slowed down to show this message  host="tcp://0.0.0.0:2375"
WARN[2023-12-15T21:40:42.853370720Z] Please consider generating tls certificates with client validation to prevent exposing unauthenticated root access to your network  host="tcp://0.0.0.0:2375"
WARN[2023-12-15T21:40:42.853436601Z] You can override this by explicitly specifying '--tls=false' or '--tlsverify=false'  host="tcp://0.0.0.0:2375"
WARN[2023-12-15T21:40:42.853452012Z] Support for listening on TCP without authentication or explicit intent to run without authentication will be removed in the next release  host="tcp://0.0.0.0:2375"
WARN[2023-12-15T21:40:57.855024630Z] could not change group /var/run/docker.sock to docker: group docker not found
INFO[2023-12-15T21:40:57.855202154Z] containerd not running, starting managed containerd
INFO[2023-12-15T21:40:57.856178647Z] started new containerd process                address=/var/run/docker/containerd/containerd.sock module=libcontainerd pid=30
INFO[2023-12-15T21:40:57.878615040Z] starting containerd                           revision=64b8a811b07ba6288238eefc14d898ee0b5b99ba version=v1.7.11
INFO[2023-12-15T21:40:57.907497173Z] loading plugin "io.containerd.event.v1.exchange"...  type=io.containerd.event.v1
INFO[2023-12-15T21:40:57.907547544Z] loading plugin "io.containerd.internal.v1.opt"...  type=io.containerd.internal.v1
INFO[2023-12-15T21:40:57.907792350Z] loading plugin "io.containerd.warning.v1.deprecations"...  type=io.containerd.warning.v1
INFO[2023-12-15T21:40:57.907817501Z] loading plugin "io.containerd.snapshotter.v1.blockfile"...  type=io.containerd.snapshotter.v1
INFO[2023-12-15T21:40:57.907885642Z] skip loading plugin "io.containerd.snapshotter.v1.blockfile"...  error="no scratch file generator: skip plugin" type=io.containerd.snapshotter.v1
INFO[2023-12-15T21:40:57.907906552Z] loading plugin "io.containerd.snapshotter.v1.devmapper"...  type=io.containerd.snapshotter.v1
WARN[2023-12-15T21:40:57.907922823Z] failed to load plugin io.containerd.snapshotter.v1.devmapper  error="devmapper not configured"
INFO[2023-12-15T21:40:57.907934383Z] loading plugin "io.containerd.snapshotter.v1.native"...  type=io.containerd.snapshotter.v1
INFO[2023-12-15T21:40:57.908092727Z] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  type=io.containerd.snapshotter.v1
INFO[2023-12-15T21:40:57.908369143Z] loading plugin "io.containerd.snapshotter.v1.aufs"...  type=io.containerd.snapshotter.v1
INFO[2023-12-15T21:40:57.913635006Z] skip loading plugin "io.containerd.snapshotter.v1.aufs"...  error="aufs is not supported (modprobe aufs failed: exit status 1 \"ip: can't find device 'aufs'\\nmodprobe: can't change directory to '/lib/modules': No such file or directory\\n\"): skip plugin" type=io.containerd.snapshotter.v1
INFO[2023-12-15T21:40:57.913674427Z] loading plugin "io.containerd.snapshotter.v1.zfs"...  type=io.containerd.snapshotter.v1
INFO[2023-12-15T21:40:57.913865222Z] skip loading plugin "io.containerd.snapshotter.v1.zfs"...  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
INFO[2023-12-15T21:40:57.913887322Z] loading plugin "io.containerd.content.v1.content"...  type=io.containerd.content.v1
INFO[2023-12-15T21:40:57.914007495Z] loading plugin "io.containerd.metadata.v1.bolt"...  type=io.containerd.metadata.v1
WARN[2023-12-15T21:40:57.914065496Z] could not use snapshotter devmapper in metadata plugin  error="devmapper not configured"
INFO[2023-12-15T21:40:57.914084066Z] metadata content store policy set             policy=shared
INFO[2023-12-15T21:40:57.918482609Z] loading plugin "io.containerd.gc.v1.scheduler"...  type=io.containerd.gc.v1
INFO[2023-12-15T21:40:57.918562331Z] loading plugin "io.containerd.differ.v1.walking"...  type=io.containerd.differ.v1
INFO[2023-12-15T21:40:57.918597992Z] loading plugin "io.containerd.lease.v1.manager"...  type=io.containerd.lease.v1
INFO[2023-12-15T21:40:57.918619863Z] loading plugin "io.containerd.streaming.v1.manager"...  type=io.containerd.streaming.v1
INFO[2023-12-15T21:40:57.918644253Z] loading plugin "io.containerd.runtime.v1.linux"...  type=io.containerd.runtime.v1
INFO[2023-12-15T21:40:57.918811847Z] loading plugin "io.containerd.monitor.v1.cgroups"...  type=io.containerd.monitor.v1
INFO[2023-12-15T21:40:57.919273038Z] loading plugin "io.containerd.runtime.v2.task"...  type=io.containerd.runtime.v2
INFO[2023-12-15T21:40:57.919452991Z] loading plugin "io.containerd.runtime.v2.shim"...  type=io.containerd.runtime.v2
INFO[2023-12-15T21:40:57.919484743Z] loading plugin "io.containerd.sandbox.store.v1.local"...  type=io.containerd.sandbox.store.v1
INFO[2023-12-15T21:40:57.919507374Z] loading plugin "io.containerd.sandbox.controller.v1.local"...  type=io.containerd.sandbox.controller.v1
INFO[2023-12-15T21:40:57.919525624Z] loading plugin "io.containerd.service.v1.containers-service"...  type=io.containerd.service.v1
INFO[2023-12-15T21:40:57.919545674Z] loading plugin "io.containerd.service.v1.content-service"...  type=io.containerd.service.v1
INFO[2023-12-15T21:40:57.919561565Z] loading plugin "io.containerd.service.v1.diff-service"...  type=io.containerd.service.v1
INFO[2023-12-15T21:40:57.919578625Z] loading plugin "io.containerd.service.v1.images-service"...  type=io.containerd.service.v1
INFO[2023-12-15T21:40:57.919596045Z] loading plugin "io.containerd.service.v1.introspection-service"...  type=io.containerd.service.v1
INFO[2023-12-15T21:40:57.919611926Z] loading plugin "io.containerd.service.v1.namespaces-service"...  type=io.containerd.service.v1
INFO[2023-12-15T21:40:57.919631026Z] loading plugin "io.containerd.service.v1.snapshots-service"...  type=io.containerd.service.v1
INFO[2023-12-15T21:40:57.919645546Z] loading plugin "io.containerd.service.v1.tasks-service"...  type=io.containerd.service.v1
INFO[2023-12-15T21:40:57.919677087Z] loading plugin "io.containerd.grpc.v1.containers"...  type=io.containerd.grpc.v1
INFO[2023-12-15T21:40:57.919696098Z] loading plugin "io.containerd.grpc.v1.content"...  type=io.containerd.grpc.v1
INFO[2023-12-15T21:40:57.919712028Z] loading plugin "io.containerd.grpc.v1.diff"...  type=io.containerd.grpc.v1
INFO[2023-12-15T21:40:57.919727758Z] loading plugin "io.containerd.grpc.v1.events"...  type=io.containerd.grpc.v1
INFO[2023-12-15T21:40:57.919743909Z] loading plugin "io.containerd.grpc.v1.images"...  type=io.containerd.grpc.v1
INFO[2023-12-15T21:40:57.919762479Z] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[2023-12-15T21:40:57.919778019Z] loading plugin "io.containerd.grpc.v1.leases"...  type=io.containerd.grpc.v1
INFO[2023-12-15T21:40:57.919794330Z] loading plugin "io.containerd.grpc.v1.namespaces"...  type=io.containerd.grpc.v1
INFO[2023-12-15T21:40:57.919809610Z] loading plugin "io.containerd.grpc.v1.sandbox-controllers"...  type=io.containerd.grpc.v1
INFO[2023-12-15T21:40:57.919826850Z] loading plugin "io.containerd.grpc.v1.sandboxes"...  type=io.containerd.grpc.v1
INFO[2023-12-15T21:40:57.919840961Z] loading plugin "io.containerd.grpc.v1.snapshots"...  type=io.containerd.grpc.v1
INFO[2023-12-15T21:40:57.919856751Z] loading plugin "io.containerd.grpc.v1.streaming"...  type=io.containerd.grpc.v1
INFO[2023-12-15T21:40:57.919872311Z] loading plugin "io.containerd.grpc.v1.tasks"...  type=io.containerd.grpc.v1
INFO[2023-12-15T21:40:57.919891292Z] loading plugin "io.containerd.transfer.v1.local"...  type=io.containerd.transfer.v1
INFO[2023-12-15T21:40:57.919920563Z] loading plugin "io.containerd.grpc.v1.transfer"...  type=io.containerd.grpc.v1
INFO[2023-12-15T21:40:57.919935374Z] loading plugin "io.containerd.grpc.v1.version"...  type=io.containerd.grpc.v1
INFO[2023-12-15T21:40:57.919949474Z] loading plugin "io.containerd.internal.v1.restart"...  type=io.containerd.internal.v1
INFO[2023-12-15T21:40:57.920042796Z] loading plugin "io.containerd.tracing.processor.v1.otlp"...  type=io.containerd.tracing.processor.v1
INFO[2023-12-15T21:40:57.920069286Z] skip loading plugin "io.containerd.tracing.processor.v1.otlp"...  error="no OpenTelemetry endpoint: skip plugin" type=io.containerd.tracing.processor.v1
INFO[2023-12-15T21:40:57.920116297Z] loading plugin "io.containerd.internal.v1.tracing"...  type=io.containerd.internal.v1
INFO[2023-12-15T21:40:57.920132368Z] skipping tracing processor initialization (no tracing plugin)  error="no OpenTelemetry endpoint: skip plugin"
INFO[2023-12-15T21:40:57.920278081Z] loading plugin "io.containerd.grpc.v1.healthcheck"...  type=io.containerd.grpc.v1
INFO[2023-12-15T21:40:57.920298541Z] loading plugin "io.containerd.nri.v1.nri"...  type=io.containerd.nri.v1
INFO[2023-12-15T21:40:57.920314162Z] NRI interface is disabled by configuration.
INFO[2023-12-15T21:40:57.920648640Z] serving...                                    address=/var/run/docker/containerd/containerd-debug.sock
INFO[2023-12-15T21:40:57.920785164Z] serving...                                    address=/var/run/docker/containerd/containerd.sock.ttrpc
INFO[2023-12-15T21:40:57.920911746Z] serving...                                    address=/var/run/docker/containerd/containerd.sock
INFO[2023-12-15T21:40:57.920997008Z] containerd successfully booted in 0.043434s
INFO[2023-12-15T21:40:58.900983259Z] Loading containers: start.
WARN[2023-12-15T21:40:58.935706389Z] Running modprobe bridge br_netfilter failed with message: ip: can't find device 'bridge'
bridge                151336  1 br_netfilter
stp                    12976  1 bridge
llc                    14552  2 bridge,stp
ip: can't find device 'br_netfilter'
br_netfilter           22256  0
bridge                151336  1 br_netfilter
modprobe: can't change directory to '/lib/modules': No such file or directory
, error: exit status 1
INFO[2023-12-15T21:40:59.498230956Z] Loading containers: done.
WARN[2023-12-15T21:40:59.513887071Z] WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/go/attack-surface/
WARN[2023-12-15T21:40:59.513914842Z] WARNING: bridge-nf-call-iptables is disabled
WARN[2023-12-15T21:40:59.513922842Z] WARNING: bridge-nf-call-ip6tables is disabled
INFO[2023-12-15T21:40:59.513943883Z] Docker daemon                                 commit=92884c2 graphdriver=overlay2 version=25.0.0-beta.2
INFO[2023-12-15T21:40:59.514081036Z] Daemon has completed initialization
INFO[2023-12-15T21:40:59.546091982Z] API listen on /var/run/docker.sock
INFO[2023-12-15T21:40:59.546096892Z] API listen on [::]:2375
time="2023-12-15T21:41:06.000786844Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-12-15T21:41:06.000902046Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-12-15T21:41:06.000920607Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-12-15T21:41:06.001128371Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.pause\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
INFO[2023-12-15T21:42:36.437838558Z] ignoring event                                container=31ca0689fcf6bc80aa7960629fe2a4767bf71342a08cdbbf01bcc0c2516a6cf9 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
INFO[2023-12-15T21:42:36.438047554Z] shim disconnected                             id=31ca0689fcf6bc80aa7960629fe2a4767bf71342a08cdbbf01bcc0c2516a6cf9 namespace=moby
WARN[2023-12-15T21:42:36.438162196Z] cleaning up after shim disconnected           id=31ca0689fcf6bc80aa7960629fe2a4767bf71342a08cdbbf01bcc0c2516a6cf9 namespace=moby
INFO[2023-12-15T21:42:36.438182847Z] cleaning up dead shim                         namespace=moby
WARN[2023-12-15T21:42:36.456385311Z] failed to close stdin: task 31ca0689fcf6bc80aa7960629fe2a4767bf71342a08cdbbf01bcc0c2516a6cf9 not found: not found
^CINFO[2023-12-15T21:42:38.223741354Z] Processing signal 'interrupt'
INFO[2023-12-15T21:42:38.225153157Z] stopping event stream following graceful shutdown  error="<nil>" module=libcontainerd namespace=moby
INFO[2023-12-15T21:42:38.225646768Z] Daemon shutdown complete
INFO[2023-12-15T21:42:38.225722230Z] stopping healthcheck following graceful shutdown  module=libcontainerd
INFO[2023-12-15T21:42:38.225751830Z] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=plugins.moby
```

I believe the `bridge` warning to be a red-herring as I see that in `docker:24.0.6-dind` which works.

I then run a `debian` container and try a `apt-get update`

```
docker run --rm -ti debian:latest
Unable to find image 'debian:latest' locally
latest: Pulling from library/debian
90e5e7d8b87a: Pull complete
Digest: sha256:133a1f2aa9e55d1c93d0ae1aaa7b94fb141265d0ee3ea677175cdb96f5f990e5
Status: Downloaded newer image for debian:latest
root@31ca0689fcf6:/# apt-get update
Ign:1 http://deb.debian.org/debian bookworm InRelease
Ign:2 http://deb.debian.org/debian bookworm-updates InRelease
Ign:3 http://deb.debian.org/debian-security bookworm-security InRelease
Ign:1 http://deb.debian.org/debian bookworm InRelease
Ign:2 http://deb.debian.org/debian bookworm-updates InRelease
Ign:3 http://deb.debian.org/debian-security bookworm-security InRelease
Ign:1 http://deb.debian.org/debian bookworm InRelease
Ign:2 http://deb.debian.org/debian bookworm-updates InRelease
Ign:3 http://deb.debian.org/debian-security bookworm-security InRelease
Err:1 http://deb.debian.org/debian bookworm InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian bookworm-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Err:3 http://deb.debian.org/debian-security bookworm-security InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists... Done
W: Failed to fetch http://deb.debian.org/debian/dists/bookworm/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/bookworm-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian-security/dists/bookworm-security/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

Network works if I run the inner container with `--net=host`.

*Host info:*
- CentOS 7
- Docker version 24.0.4, build 3713ee1
- Kernel: 3.10.0-1160.15.2.el7.x86_64

### LINKED ISSUE #467: ip tables legacy vs nf_tables issue persists
For us, the issue described in https://github.com/docker-library/docker/issues/463  persists, even after the fix. Our host image is a Google COS 105.

Initially I added my findings as a comment to #466, but after getting the logs, the problems looks different than the one described there.

What we observe is that the host uses a legacy ip tables version, but the `nf_tables` kernel module is present and loads fine. My guess is, that this makes the fix ineffective, because it uses `modprobe nf_tables` to determine which iptables version to use.

```
instance-1 /home/user # iptables --version
iptables v1.8.5 (legacy)
instance-1 /home/user # modprobe nf_tables
instance-1 /home/user # lsmod
Module                  Size  Used by
nf_tables             262144  0
xt_MASQUERADE          16384  1
iptable_nat            16384  1
nf_nat                 40960  2 iptable_nat,xt_MASQUERADE
xt_addrtype            16384  2
br_netfilter           24576  0
xt_state               16384  0
aesni_intel           385024  0
crypto_simd            16384  1 aesni_intel
virtio_balloon         24576  0
cryptd                 24576  1 crypto_simd
loadpin_trigger        12288  0
fuse                  147456  1
configfs               40960  1
```

Running the latest dind image on this system shows the original error.

```
# docker run --rm -ti --privileged --name docker -e DOCKER_TLS_CERTDIR= -p 2375:2375 docker:dind
Unable to find image 'docker:dind' locally
dind: Pulling from library/docker
661ff4d9561e: Already exists 
b94b6133cd82: Pull complete 
4f4fb700ef54: Pull complete 
de090124fc79: Pull complete 
f04b53a848df: Pull complete 
69c523561410: Pull complete 
64a7d03e6f4c: Pull complete 
ace0118efca4: Pull complete 
80554da1d9db: Pull complete 
361bd5a92831: Pull complete 
33610589f742: Pull complete 
fd848af64097: Pull complete 
a4753775b651: Pull complete 
1c63dcb22ce0: Pull complete 
47ce6921876b: Pull complete 
Digest: sha256:1b9844d846ce3a6a6af7013e999a373112c3c0450aca49e155ae444526a2c45e
Status: Downloaded newer image for docker:dind
INFO[2023-12-18T13:13:44.521579775Z] Starting up                                  
WARN[2023-12-18T13:13:44.522763392Z] Binding to IP address without --tlsverify is insecure and gives root access on this machine to everyone who has access to your network.  host="tcp://0.0.0.0:2375"
WARN[2023-12-18T13:13:44.522798300Z] Binding to an IP address, even on localhost, can also give access to scripts run in a browser. Be safe out there!  host="tcp://0.0.0.0:2375"
WARN[2023-12-18T13:13:45.523079789Z] Binding to an IP address without --tlsverify is deprecated. Startup is intentionally being slowed down to show this message  host="tcp://0.0.0.0:2375"
WARN[2023-12-18T13:13:45.523172032Z] Please consider generating tls certificates with client validation to prevent exposing unauthenticated root access to your network  host="tcp://0.0.0.0:2375"
WARN[2023-12-18T13:13:45.523190207Z] You can override this by explicitly specifying '--tls=false' or '--tlsverify=false'  host="tcp://0.0.0.0:2375"
WARN[2023-12-18T13:13:45.523209207Z] Support for listening on TCP without authentication or explicit intent to run without authentication will be removed in the next release  host="tcp://0.0.0.0:2375"
WARN[2023-12-18T13:14:00.530905003Z] could not change group /var/run/docker.sock to docker: group docker not found 
INFO[2023-12-18T13:14:00.531159702Z] containerd not running, starting managed containerd 
INFO[2023-12-18T13:14:00.532430404Z] started new containerd process                address=/var/run/docker/containerd/containerd.sock module=libcontainerd pid=28
INFO[2023-12-18T13:14:00.561175645Z] starting containerd                           revision=091922f03c2762540fd057fba91260237ff86acb version=v1.7.6
INFO[2023-12-18T13:14:00.589959772Z] loading plugin "io.containerd.snapshotter.v1.aufs"...  type=io.containerd.snapshotter.v1
INFO[2023-12-18T13:14:00.595938320Z] skip loading plugin "io.containerd.snapshotter.v1.aufs"...  error="aufs is not supported (modprobe aufs failed: exit status 1 \"ip: can't find device 'aufs'\\nmodprobe: can't change directory to '/lib/modules': No such file or directory\\n\"): skip plugin" type=io.containerd.snapshotter.v1
INFO[2023-12-18T13:14:00.595991142Z] loading plugin "io.containerd.content.v1.content"...  type=io.containerd.content.v1
INFO[2023-12-18T13:14:00.596225412Z] loading plugin "io.containerd.snapshotter.v1.blockfile"...  type=io.containerd.snapshotter.v1
INFO[2023-12-18T13:14:00.596332335Z] skip loading plugin "io.containerd.snapshotter.v1.blockfile"...  error="no scratch file generator: skip plugin" type=io.containerd.snapshotter.v1
INFO[2023-12-18T13:14:00.596362661Z] loading plugin "io.containerd.snapshotter.v1.native"...  type=io.containerd.snapshotter.v1
INFO[2023-12-18T13:14:00.596483188Z] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  type=io.containerd.snapshotter.v1
INFO[2023-12-18T13:14:00.596855086Z] loading plugin "io.containerd.snapshotter.v1.devmapper"...  type=io.containerd.snapshotter.v1
WARN[2023-12-18T13:14:00.596891420Z] failed to load plugin io.containerd.snapshotter.v1.devmapper  error="devmapper not configured"
INFO[2023-12-18T13:14:00.596916005Z] loading plugin "io.containerd.snapshotter.v1.zfs"...  type=io.containerd.snapshotter.v1
INFO[2023-12-18T13:14:00.597122856Z] skip loading plugin "io.containerd.snapshotter.v1.zfs"...  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
INFO[2023-12-18T13:14:00.597156199Z] loading plugin "io.containerd.metadata.v1.bolt"...  type=io.containerd.metadata.v1
WARN[2023-12-18T13:14:00.597298896Z] could not use snapshotter devmapper in metadata plugin  error="devmapper not configured"
INFO[2023-12-18T13:14:00.597331009Z] metadata content store policy set             policy=shared
INFO[2023-12-18T13:14:00.604591337Z] loading plugin "io.containerd.differ.v1.walking"...  type=io.containerd.differ.v1
INFO[2023-12-18T13:14:00.604657262Z] loading plugin "io.containerd.event.v1.exchange"...  type=io.containerd.event.v1
INFO[2023-12-18T13:14:00.604686106Z] loading plugin "io.containerd.gc.v1.scheduler"...  type=io.containerd.gc.v1
INFO[2023-12-18T13:14:00.604861864Z] loading plugin "io.containerd.lease.v1.manager"...  type=io.containerd.lease.v1
INFO[2023-12-18T13:14:00.604904110Z] loading plugin "io.containerd.nri.v1.nri"...  type=io.containerd.nri.v1
INFO[2023-12-18T13:14:00.604947603Z] NRI interface is disabled by configuration.  
INFO[2023-12-18T13:14:00.604975839Z] loading plugin "io.containerd.runtime.v2.task"...  type=io.containerd.runtime.v2
INFO[2023-12-18T13:14:00.605356221Z] loading plugin "io.containerd.runtime.v2.shim"...  type=io.containerd.runtime.v2
INFO[2023-12-18T13:14:00.605412576Z] loading plugin "io.containerd.sandbox.store.v1.local"...  type=io.containerd.sandbox.store.v1
INFO[2023-12-18T13:14:00.605445555Z] loading plugin "io.containerd.sandbox.controller.v1.local"...  type=io.containerd.sandbox.controller.v1
INFO[2023-12-18T13:14:00.605560451Z] loading plugin "io.containerd.streaming.v1.manager"...  type=io.containerd.streaming.v1
INFO[2023-12-18T13:14:00.605596705Z] loading plugin "io.containerd.service.v1.introspection-service"...  type=io.containerd.service.v1
INFO[2023-12-18T13:14:00.605689046Z] loading plugin "io.containerd.service.v1.containers-service"...  type=io.containerd.service.v1
INFO[2023-12-18T13:14:00.605721188Z] loading plugin "io.containerd.service.v1.content-service"...  type=io.containerd.service.v1
INFO[2023-12-18T13:14:00.605748528Z] loading plugin "io.containerd.service.v1.diff-service"...  type=io.containerd.service.v1
INFO[2023-12-18T13:14:00.605777483Z] loading plugin "io.containerd.service.v1.images-service"...  type=io.containerd.service.v1
INFO[2023-12-18T13:14:00.605807563Z] loading plugin "io.containerd.service.v1.namespaces-service"...  type=io.containerd.service.v1
INFO[2023-12-18T13:14:00.605872028Z] loading plugin "io.containerd.service.v1.snapshots-service"...  type=io.containerd.service.v1
INFO[2023-12-18T13:14:00.605925160Z] loading plugin "io.containerd.runtime.v1.linux"...  type=io.containerd.runtime.v1
INFO[2023-12-18T13:14:00.606415193Z] loading plugin "io.containerd.monitor.v1.cgroups"...  type=io.containerd.monitor.v1
INFO[2023-12-18T13:14:00.607063136Z] loading plugin "io.containerd.service.v1.tasks-service"...  type=io.containerd.service.v1
INFO[2023-12-18T13:14:00.607141118Z] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[2023-12-18T13:14:00.607176859Z] loading plugin "io.containerd.transfer.v1.local"...  type=io.containerd.transfer.v1
INFO[2023-12-18T13:14:00.607236131Z] loading plugin "io.containerd.internal.v1.restart"...  type=io.containerd.internal.v1
INFO[2023-12-18T13:14:00.607375475Z] loading plugin "io.containerd.grpc.v1.containers"...  type=io.containerd.grpc.v1
INFO[2023-12-18T13:14:00.607547801Z] loading plugin "io.containerd.grpc.v1.content"...  type=io.containerd.grpc.v1
INFO[2023-12-18T13:14:00.607612774Z] loading plugin "io.containerd.grpc.v1.diff"...  type=io.containerd.grpc.v1
INFO[2023-12-18T13:14:00.607662706Z] loading plugin "io.containerd.grpc.v1.events"...  type=io.containerd.grpc.v1
INFO[2023-12-18T13:14:00.607760235Z] loading plugin "io.containerd.grpc.v1.healthcheck"...  type=io.containerd.grpc.v1
INFO[2023-12-18T13:14:00.607884384Z] loading plugin "io.containerd.grpc.v1.images"...  type=io.containerd.grpc.v1
INFO[2023-12-18T13:14:00.607987809Z] loading plugin "io.containerd.grpc.v1.leases"...  type=io.containerd.grpc.v1
INFO[2023-12-18T13:14:00.608089132Z] loading plugin "io.containerd.grpc.v1.namespaces"...  type=io.containerd.grpc.v1
INFO[2023-12-18T13:14:00.608142939Z] loading plugin "io.containerd.internal.v1.opt"...  type=io.containerd.internal.v1
INFO[2023-12-18T13:14:00.608937899Z] loading plugin "io.containerd.grpc.v1.sandbox-controllers"...  type=io.containerd.grpc.v1
INFO[2023-12-18T13:14:00.608994893Z] loading plugin "io.containerd.grpc.v1.sandboxes"...  type=io.containerd.grpc.v1
INFO[2023-12-18T13:14:00.609209691Z] loading plugin "io.containerd.grpc.v1.snapshots"...  type=io.containerd.grpc.v1
INFO[2023-12-18T13:14:00.609341346Z] loading plugin "io.containerd.grpc.v1.streaming"...  type=io.containerd.grpc.v1
INFO[2023-12-18T13:14:00.609445949Z] loading plugin "io.containerd.grpc.v1.tasks"...  type=io.containerd.grpc.v1
INFO[2023-12-18T13:14:00.609550860Z] loading plugin "io.containerd.grpc.v1.transfer"...  type=io.containerd.grpc.v1
INFO[2023-12-18T13:14:00.609590249Z] loading plugin "io.containerd.grpc.v1.version"...  type=io.containerd.grpc.v1
INFO[2023-12-18T13:14:00.609913936Z] loading plugin "io.containerd.tracing.processor.v1.otlp"...  type=io.containerd.tracing.processor.v1
INFO[2023-12-18T13:14:00.610045474Z] skip loading plugin "io.containerd.tracing.processor.v1.otlp"...  error="no OpenTelemetry endpoint: skip plugin" type=io.containerd.tracing.processor.v1
INFO[2023-12-18T13:14:00.610077683Z] loading plugin "io.containerd.internal.v1.tracing"...  type=io.containerd.internal.v1
INFO[2023-12-18T13:14:00.610100824Z] skipping tracing processor initialization (no tracing plugin)  error="no OpenTelemetry endpoint: skip plugin"
INFO[2023-12-18T13:14:00.611554872Z] serving...                                    address=/var/run/docker/containerd/containerd-debug.sock
INFO[2023-12-18T13:14:00.611716968Z] serving...                                    address=/var/run/docker/containerd/containerd.sock.ttrpc
INFO[2023-12-18T13:14:00.612008773Z] serving...                                    address=/var/run/docker/containerd/containerd.sock
INFO[2023-12-18T13:14:00.612417211Z] containerd successfully booted in 0.052245s  
INFO[2023-12-18T13:14:00.647188074Z] Loading containers: start.                   
INFO[2023-12-18T13:14:00.710654054Z] stopping event stream following graceful shutdown  error="<nil>" module=libcontainerd namespace=moby
INFO[2023-12-18T13:14:00.711183969Z] stopping healthcheck following graceful shutdown  module=libcontainerd
INFO[2023-12-18T13:14:00.711556381Z] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=plugins.moby
failed to start daemon: Error initializing network controller: error obtaining controller instance: unable to add return rule in DOCKER-ISOLATION-STAGE-1 chain:  (iptables failed: iptables --wait -A DOCKER-ISOLATION-STAGE-1 -j RETURN: iptables v1.8.10 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain DOCKER-ISOLATION-STAGE-1
 (exit status 4))
```

### PR DESCRIPTION
**Pull request by tianon**
The nature of `modprobe` in this image is that it works via `ip` hacks, but the exit code will always be non-zero because we don't have `/lib/modules` from the host.

The effect of this was that everyone was using `iptables-legacy` (whether it was warranted for them to be doing so or not).

This probably fixes #466
This probably also fixes #467

### CODE REVIEW

**Review by yosifkit — APPROVED** [review]

File: dockerd-entrypoint.sh [hunk 1]
```diff
@@ -148,10 +148,14 @@ if [ "$1" = 'dockerd' ]; then
...
+		if ! iptables -nL > /dev/null 2>&1; then
+			# might be host has no nf_tables, but Alpine is all-in now (so let's try a legacy fallback)
 			modprobe ip_tables || :
-			# see https://github.com/docker-library/docker/issues/463 (and the dind Dockerfile where this directory is set up)
-			export PATH="/usr/local/sbin/.iptables-legacy:$PATH"
+			if /usr/local/sbin/.iptables-legacy/iptables -nL > /dev/null 2>&1; then
+				# see https://github.com/docker-library/docker/issues/463 (and the dind Dockerfile where this directory is set up)
+				export PATH="/usr/local/sbin/.iptables-legacy:$PATH"
+			fi
 		fi
```
Comment (comel) [inline dockerd-entrypoint.sh:159]: When host has both `nf_tables` and `ip_tables` but is using `ip_tables`, `iptables` is giving this warning:

```
iptables -nL >/dev/null
# Warning: iptables-legacy tables present, use iptables-legacy to see them
```
Something like this worked for me to detect that case and use `iptables-legacy`:

```
        elif iptables -nL 2>&1 >/dev/null | grep -q tables-legacy; then
                export PATH="/usr/local/sbin/.iptables-legacy:$PATH"
```

**Comment by stevexuereb** [comment]
I was asked to test this on GitLab's infrastructure in https://github.com/docker-library/docker/issues/463#issuecomment-1861821236 below are the test results which are successful 🎉 :

```sh
# Spin up server with our imae
$ gcloud compute instances create docker-test-cos-85 --image cos-85-13310-1498-7 --image-project cos-cloud --zone=us-east1-c

# Build image
$ gcloud compute ssh docker-test-cos-85
$ docker build --pull 'https://github.com/docker-library/docker.git#refs/pull/468/merge:24/dind'

# Start Docker image
steve@docker-test-cos-85 ~ $ docker run --privileged --rm -it 10bb05416255
Certificate request self-signature ok
subject=CN = docker:dind server
/certs/server/cert.pem: OK
Certificate request self-signature ok
subject=CN = docker:dind client
/certs/client/cert.pem: OK
ip: can't find device 'nf_tables'
modprobe: can't change directory to '/lib/modules': No such file or directory
ip: can't find device 'ip_tables'
modprobe: can't change directory to '/lib/modules': No such file or directory
INFO[2023-12-19T10:25:43.763856164Z] Starting up
...
INFO[2023-12-19T10:25:43.850111407Z] containerd successfully booted in 0.054331s
INFO[2023-12-19T10:25:43.892042049Z] Loading containers: start.
INFO[2023-12-19T10:25:43.978291484Z] Loading containers: done.
INFO[2023-12-19T10:25:43.991579126Z] Docker daemon                                 commit=311b9ff graphdriver=overlay2 version=24.0.7
INFO[2023-12-19T10:25:43.992161922Z] Daemon has completed initialization
INFO[2023-12-19T10:25:44.036184473Z] API listen on /var/run/docker.sock
INFO[2023-12-19T10:25:44.036664068Z] API listen on [::]:2376
```

<details>
<summary> build logs </summary>

```sh
Sending build context to Docker daemon  14.34kB
Step 1/12 : FROM docker:24-cli
24-cli: Pulling from library/docker
661ff4d9561e: Pull complete
b94b6133cd82: Pull complete
4f4fb700ef54: Pull complete
de090124fc79: Pull complete
f04b53a848df: Pull complete
69c523561410: Pull complete
64a7d03e6f4c: Pull complete
ace0118efca4: Pull complete
80554da1d9db: Pull complete
Digest: sha256:1d835c53466737f96cc5a85e94a575acef9bdfb02da59dc21b82653fd4f1d1eb
Status: Downloaded newer image for docker:24-cli
 ---> cbdc7727a012
Step 2/12 : RUN set -eux;       apk add --no-cache              btrfs-progs             e2fsprogs               e2fsprogs-extra                 ip6tables               iptables                openssl                 shadow-uidmap           xfsprogs                xz              pigz    ;       if zfs="$(apk info --no-cache --quiet zfs)" && [ -n "$zfs" ]; then           apk add --no-cache zfs;         fi
 ---> Running in 3dc9d71aea25
+ apk add --no-cache btrfs-progs e2fsprogs e2fsprogs-extra ip6tables iptables openssl shadow-uidmap xfsprogs xz pigz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
(1/28) Installing libblkid (2.39.3-r0)
(2/28) Installing lzo (2.10-r5)
(3/28) Installing eudev-libs (3.2.14-r0)
(4/28) Installing libuuid (2.39.3-r0)
(5/28) Installing zstd-libs (1.5.5-r8)
(6/28) Installing btrfs-progs (6.6.2-r0)
(7/28) Installing libcom_err (1.47.0-r5)
(8/28) Installing e2fsprogs-libs (1.47.0-r5)
(9/28) Installing e2fsprogs (1.47.0-r5)
(10/28) Installing e2fsprogs-extra (1.47.0-r5)
(11/28) Installing libmnl (1.0.5-r2)
(12/28) Installing libnftnl (1.2.6-r0)
(13/28) Installing libxtables (1.8.10-r1)
(14/28) Installing iptables (1.8.10-r1)
(15/28) Installing openssl (3.1.4-r2)
(16/28) Installing pigz (2.8-r0)
(17/28) Installing libmd (1.1.0-r0)
(18/28) Installing libbsd (0.11.7-r3)
(19/28) Installing skalibs (2.14.0.1-r0)
(20/28) Installing utmps-libs (0.1.2.2-r0)
(21/28) Installing linux-pam (1.5.3-r7)
(22/28) Installing shadow-libs (4.14.2-r0)
(23/28) Installing shadow-subids (4.14.2-r0)
(24/28) Installing inih (57-r1)
(25/28) Installing userspace-rcu (0.14.0-r2)
(26/28) Installing xfsprogs (6.5.0-r0)
(27/28) Installing xz-libs (5.4.5-r0)
(28/28) Installing xz (5.4.5-r0)
Executing busybox-1.36.1-r15.trigger
OK: 24 MiB in 50 packages
+ apk info --no-cache --quiet zfs
+ zfs='zfs-2.2.2-r0 description:
Advanced filesystem and volume manager

zfs-2.2.2-r0 webpage:
https://openzfs.org

zfs-2.2.2-r0 installed size:
1396 KiB'
+ '[' -n 'zfs-2.2.2-r0 description:
Advanced filesystem and volume manager

zfs-2.2.2-r0 webpage:
https://openzfs.org

zfs-2.2.2-r0 installed size:
1396 KiB' ]
+ apk add --no-cache zfs
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
(1/9) Installing libintl (0.22.3-r0)
(2/9) Installing libtirpc-conf (1.3.4-r0)
(3/9) Installing krb5-conf (1.0-r2)
(4/9) Installing keyutils-libs (1.6.3-r3)
(5/9) Installing libverto (0.3.2-r2)
(6/9) Installing krb5-libs (1.21.2-r0)
(7/9) Installing libtirpc (1.3.4-r0)
(8/9) Installing zfs-libs (2.2.2-r0)
(9/9) Installing zfs (2.2.2-r0)
Executing busybox-1.36.1-r15.trigger
OK: 31 MiB in 59 packages
Removing intermediate container 3dc9d71aea25
 ---> aa06f320d2f5
Step 3/12 : RUN set -eux;       apk add --no-cache iptables-legacy;     mkdir -p /usr/local/sbin/.iptables-legacy;      for f in                iptables                iptables-save           iptables-restore                ip6tables               ip6tables-save          ip6tables-restore       ; do            b="/sbin/${f/tables/tables-legacy}";                 "$b" --version;                 ln -svT "$b" "/usr/local/sbin/.iptables-legacy/$f";     done;   export PATH="/usr/local/sbin/.iptables-legacy:$PATH";   iptables --version | grep legacy
 ---> Running in c3f3ccab0cbe
+ apk add --no-cache iptables-legacy
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
(1/3) Installing libip4tc (1.8.10-r1)
(2/3) Installing libip6tc (1.8.10-r1)
(3/3) Installing iptables-legacy (1.8.10-r1)
Executing busybox-1.36.1-r15.trigger
OK: 32 MiB in 62 packages
+ mkdir -p /usr/local/sbin/.iptables-legacy
+ b=/sbin/iptables-legacy
+ /sbin/iptables-legacy --version
iptables v1.8.10 (legacy)
+ ln -svT /sbin/iptables-legacy /usr/local/sbin/.iptables-legacy/iptables
'/usr/local/sbin/.iptables-legacy/iptables' -> '/sbin/iptables-legacy'
+ b=/sbin/iptables-legacy-save
+ /sbin/iptables-legacy-save --version
iptables-save v1.8.10 (legacy)
+ ln -svT /sbin/iptables-legacy-save /usr/local/sbin/.iptables-legacy/iptables-save
'/usr/local/sbin/.iptables-legacy/iptables-save' -> '/sbin/iptables-legacy-save'
+ b=/sbin/iptables-legacy-restore
+ /sbin/iptables-legacy-restore --version
iptables-restore v1.8.10 (legacy)
+ ln -svT /sbin/iptables-legacy-restore /usr/local/sbin/.iptables-legacy/iptables-restore
'/usr/local/sbin/.iptables-legacy/iptables-restore' -> '/sbin/iptables-legacy-restore'
+ b=/sbin/ip6tables-legacy
+ /sbin/ip6tables-legacy --version
ip6tables v1.8.10 (legacy)
+ ln -svT /sbin/ip6tables-legacy /usr/local/sbin/.iptables-legacy/ip6tables
+ b=/sbin/ip6tables-legacy-save
+ /sbin/ip6tables-legacy-save --version
'/usr/local/sbin/.iptables-legacy/ip6tables' -> '/sbin/ip6tables-legacy'
ip6tables-save v1.8.10 (legacy)
+ ln -svT /sbin/ip6tables-legacy-save /usr/local/sbin/.iptables-legacy/ip6tables-save
'/usr/local/sbin/.iptables-legacy/ip6tables-save' -> '/sbin/ip6tables-legacy-save'
+ b=/sbin/ip6tables-legacy-restore
+ /sbin/ip6tables-legacy-restore --version
ip6tables-restore v1.8.10 (legacy)
+ ln -svT /sbin/ip6tables-legacy-restore /usr/local/sbin/.iptables-legacy/ip6tables-restore
'/usr/local/sbin/.iptables-legacy/ip6tables-restore' -> '/sbin/ip6tables-legacy-restore'
+ export 'PATH=/usr/local/sbin/.iptables-legacy:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
+ grep legacy
+ iptables --version
iptables v1.8.10 (legacy)
Removing intermediate container c3f3ccab0cbe
 ---> 85cc7d1d3221
Step 4/12 : RUN set -eux;       addgroup -S dockremap;  adduser -S -G dockremap dockremap;      echo 'dockremap:165536:65536' >> /etc/subuid;   echo 'dockremap:165536:65536' >> /etc/subgid
 ---> Running in 1403f02d15d5
+ addgroup -S dockremap
+ adduser -S -G dockremap dockremap
+ echo dockremap:165536:65536
+ echo dockremap:165536:65536
Removing intermediate container 1403f02d15d5
 ---> f459e96929b0
Step 5/12 : RUN set -eux;               apkArch="$(apk --print-arch)";  case "$apkArch" in              'x86_64')                       url='https://download.docker.com/linux/static/stable/x86_64/docker-24.0.7.tgz';                         ;;              'armhf')                        url='https://download.docker.com/linux/static/stable/armel/docker-24.0.7.tgz';                       ;;              'armv7')                        url='https://download.docker.com/linux/static/stable/armhf/docker-24.0.7.tgz';                  ;;              'aarch64')                      url='https://download.docker.com/linux/static/stable/aarch64/docker-24.0.7.tgz';                     ;;              *) echo >&2 "error: unsupported 'docker.tgz' architecture ($apkArch)"; exit 1 ;;        esac;           wget -O 'docker.tgz' "$url";            tar --extract           --file docker.tgz               --strip-components 1            --directory /usr/local/bin/          --no-same-owner                 --exclude 'docker/docker'       ;       rm docker.tgz;          dockerd --version;      containerd --version;   ctr --version;  runc --version
 ---> Running in ce56712e529b
+ apk --print-arch
+ apkArch=x86_64
+ url=https://download.docker.com/linux/static/stable/x86_64/docker-24.0.7.tgz
+ wget -O docker.tgz https://download.docker.com/linux/static/stable/x86_64/docker-24.0.7.tgz
Connecting to download.docker.com (3.161.193.14:443)
saving to 'docker.tgz'
docker.tgz            46% |**************                  | 30.9M  0:00:01 ETA
docker.tgz           100% |********************************| 66.5M  0:00:00 ETA
'docker.tgz' saved
+ tar --extract --file docker.tgz --strip-components 1 --directory /usr/local/bin/ --no-same-owner --exclude docker/docker
+ rm docker.tgz
+ dockerd --version
Docker version 24.0.7, build 311b9ff
+ containerd --version
containerd github.com/containerd/containerd v1.7.6 091922f03c2762540fd057fba91260237ff86acb
+ ctr --version
ctr github.com/containerd/containerd v1.7.6
+ runc --version
runc version 1.1.9
commit: v1.1.9-0-gccaecfc
spec: 1.0.2-dev
go: go1.20.10
libseccomp: 2.5.1
Removing intermediate container ce56712e529b
 ---> e88711b42fe2
Step 6/12 : ENV DIND_COMMIT 65cfcc28ab37cb75e1560e4b4738719c07c6618e
 ---> Running in 15f53b4abdb0
Removing intermediate container 15f53b4abdb0
 ---> fb163af82a2d
Step 7/12 : RUN set -eux;       wget -O /usr/local/bin/dind "https://raw.githubusercontent.com/docker/docker/${DIND_COMMIT}/hack/dind";         chmod +x /usr/local/bin/dind
 ---> Running in 1d3acb077218
+ wget -O /usr/local/bin/dind https://raw.githubusercontent.com/docker/docker/65cfcc28ab37cb75e1560e4b4738719c07c6618e/hack/dind
Connecting to raw.githubusercontent.com (185.199.111.133:443)
saving to '/usr/local/bin/dind'
dind                 100% |********************************|  2862  0:00:00 ETA
'/usr/local/bin/dind' saved
+ chmod +x /usr/local/bin/dind
Removing intermediate container 1d3acb077218
 ---> 197cda935b46
Step 8/12 : COPY dockerd-entrypoint.sh /usr/local/bin/
 ---> c0451e74e59b
Step 9/12 : VOLUME /var/lib/docker
 ---> Running in 75ea4536b7d4
Removing intermediate container 75ea4536b7d4
 ---> d2aee2b96022
Step 10/12 : EXPOSE 2375 2376
 ---> Running in 3c8d45fc03fd
Removing intermediate container 3c8d45fc03fd
 ---> 595b1de6da78
Step 11/12 : ENTRYPOINT ["dockerd-entrypoint.sh"]
 ---> Running in 2df28603eea9
Removing intermediate container 2df28603eea9
 ---> dc532f8177ca
Step 12/12 : CMD []
 ---> Running in 1f73f5f7eaa6
Removing intermediate container 1f73f5f7eaa6
 ---> 10bb05416255
Successfully built 10bb05416255
```

</details>

<details>
<summary> start up logs </summary>

```
Certificate request self-signature ok
subject=CN = docker:dind server
/certs/server/cert.pem: OK
Certificate request self-signature ok
subject=CN = docker:dind client
/certs/client/cert.pem: OK
ip: can't find device 'nf_tables'
modprobe: can't change directory to '/lib/modules': No such file or directory
ip: can't find device 'ip_tables'
modprobe: can't change directory to '/lib/modules': No such file or directory
INFO[2023-12-19T10:25:43.763856164Z] Starting up
WARN[2023-12-19T10:25:43.767709129Z] could not change group /var/run/docker.sock to docker: group docker not found
INFO[2023-12-19T10:25:43.768177577Z] containerd not running, starting managed containerd
INFO[2023-12-19T10:25:43.788860160Z] started new containerd process                address=/var/run/docker/containerd/containerd.sock module=libcontainerd pid=62
INFO[2023-12-19T10:25:43.796565663Z] starting containerd                           revision=091922f03c2762540fd057fba91260237ff86acb version=v1.7.6
INFO[2023-12-19T10:25:43.822393856Z] loading plugin "io.containerd.snapshotter.v1.aufs"...  type=io.containerd.snapshotter.v1
INFO[2023-12-19T10:25:43.827147221Z] skip loading plugin "io.containerd.snapshotter.v1.aufs"...  error="aufs is not supported (modprobe aufs failed: exit status 1 \"ip: can't find device 'aufs'\\nmodprobe: can't change directory to '/lib/modules': No such file or directory\\n\"): skip plugin" type=io.containerd.snapshotter.v1
INFO[2023-12-19T10:25:43.827587958Z] loading plugin "io.containerd.content.v1.content"...  type=io.containerd.content.v1
INFO[2023-12-19T10:25:43.827946063Z] loading plugin "io.containerd.snapshotter.v1.blockfile"...  type=io.containerd.snapshotter.v1
INFO[2023-12-19T10:25:43.828268888Z] skip loading plugin "io.containerd.snapshotter.v1.blockfile"...  error="no scratch file generator: skip plugin" type=io.containerd.snapshotter.v1
INFO[2023-12-19T10:25:43.828486950Z] loading plugin "io.containerd.snapshotter.v1.native"...  type=io.containerd.snapshotter.v1
INFO[2023-12-19T10:25:43.828765624Z] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  type=io.containerd.snapshotter.v1
INFO[2023-12-19T10:25:43.829292901Z] loading plugin "io.containerd.snapshotter.v1.devmapper"...  type=io.containerd.snapshotter.v1
WARN[2023-12-19T10:25:43.829552796Z] failed to load plugin io.containerd.snapshotter.v1.devmapper  error="devmapper not configured"
INFO[2023-12-19T10:25:43.829752351Z] loading plugin "io.containerd.snapshotter.v1.zfs"...  type=io.containerd.snapshotter.v1
INFO[2023-12-19T10:25:43.830185103Z] skip loading plugin "io.containerd.snapshotter.v1.zfs"...  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
INFO[2023-12-19T10:25:43.830413003Z] loading plugin "io.containerd.metadata.v1.bolt"...  type=io.containerd.metadata.v1
WARN[2023-12-19T10:25:43.830672780Z] could not use snapshotter devmapper in metadata plugin  error="devmapper not configured"
INFO[2023-12-19T10:25:43.830878614Z] metadata content store policy set             policy=shared
INFO[2023-12-19T10:25:43.841062065Z] loading plugin "io.containerd.differ.v1.walking"...  type=io.containerd.differ.v1
INFO[2023-12-19T10:25:43.841462101Z] loading plugin "io.containerd.event.v1.exchange"...  type=io.containerd.event.v1
INFO[2023-12-19T10:25:43.841688874Z] loading plugin "io.containerd.gc.v1.scheduler"...  type=io.containerd.gc.v1
INFO[2023-12-19T10:25:43.841994584Z] loading plugin "io.containerd.lease.v1.manager"...  type=io.containerd.lease.v1
INFO[2023-12-19T10:25:43.842232622Z] loading plugin "io.containerd.nri.v1.nri"...  type=io.containerd.nri.v1
INFO[2023-12-19T10:25:43.842390326Z] NRI interface is disabled by configuration.
INFO[2023-12-19T10:25:43.842548877Z] loading plugin "io.containerd.runtime.v2.task"...  type=io.containerd.runtime.v2
INFO[2023-12-19T10:25:43.843077443Z] loading plugin "io.containerd.runtime.v2.shim"...  type=io.containerd.runtime.v2
INFO[2023-12-19T10:25:43.843310782Z] loading plugin "io.containerd.sandbox.store.v1.local"...  type=io.containerd.sandbox.store.v1
INFO[2023-12-19T10:25:43.843494442Z] loading plugin "io.containerd.sandbox.controller.v1.local"...  type=io.containerd.sandbox.controller.v1
INFO[2023-12-19T10:25:43.843721326Z] loading plugin "io.containerd.streaming.v1.manager"...  type=io.containerd.streaming.v1
INFO[2023-12-19T10:25:43.843896820Z] loading plugin "io.containerd.service.v1.introspection-service"...  type=io.containerd.service.v1
INFO[2023-12-19T10:25:43.844076186Z] loading plugin "io.containerd.service.v1.containers-service"...  type=io.containerd.service.v1
INFO[2023-12-19T10:25:43.844259092Z] loading plugin "io.containerd.service.v1.content-service"...  type=io.containerd.service.v1
INFO[2023-12-19T10:25:43.844439127Z] loading plugin "io.containerd.service.v1.diff-service"...  type=io.containerd.service.v1
INFO[2023-12-19T10:25:43.844613034Z] loading plugin "io.containerd.service.v1.images-service"...  type=io.containerd.service.v1
INFO[2023-12-19T10:25:43.844806103Z] loading plugin "io.containerd.service.v1.namespaces-service"...  type=io.containerd.service.v1
INFO[2023-12-19T10:25:43.844976196Z] loading plugin "io.containerd.service.v1.snapshots-service"...  type=io.containerd.service.v1
INFO[2023-12-19T10:25:43.845077128Z] loading plugin "io.containerd.runtime.v1.linux"...  type=io.containerd.runtime.v1
INFO[2023-12-19T10:25:43.845544661Z] loading plugin "io.containerd.monitor.v1.cgroups"...  type=io.containerd.monitor.v1
INFO[2023-12-19T10:25:43.846199867Z] loading plugin "io.containerd.service.v1.tasks-service"...  type=io.containerd.service.v1
INFO[2023-12-19T10:25:43.846427968Z] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[2023-12-19T10:25:43.846670199Z] loading plugin "io.containerd.transfer.v1.local"...  type=io.containerd.transfer.v1
INFO[2023-12-19T10:25:43.846902808Z] loading plugin "io.containerd.internal.v1.restart"...  type=io.containerd.internal.v1
INFO[2023-12-19T10:25:43.847248050Z] loading plugin "io.containerd.grpc.v1.containers"...  type=io.containerd.grpc.v1
INFO[2023-12-19T10:25:43.847306089Z] loading plugin "io.containerd.grpc.v1.content"...  type=io.containerd.grpc.v1
INFO[2023-12-19T10:25:43.847328827Z] loading plugin "io.containerd.grpc.v1.diff"...  type=io.containerd.grpc.v1
INFO[2023-12-19T10:25:43.847351193Z] loading plugin "io.containerd.grpc.v1.events"...  type=io.containerd.grpc.v1
INFO[2023-12-19T10:25:43.847430123Z] loading plugin "io.containerd.grpc.v1.healthcheck"...  type=io.containerd.grpc.v1
INFO[2023-12-19T10:25:43.847463689Z] loading plugin "io.containerd.grpc.v1.images"...  type=io.containerd.grpc.v1
INFO[2023-12-19T10:25:43.847583614Z] loading plugin "io.containerd.grpc.v1.leases"...  type=io.containerd.grpc.v1
INFO[2023-12-19T10:25:43.847615842Z] loading plugin "io.containerd.grpc.v1.namespaces"...  type=io.containerd.grpc.v1
INFO[2023-12-19T10:25:43.847653324Z] loading plugin "io.containerd.internal.v1.opt"...  type=io.containerd.internal.v1
INFO[2023-12-19T10:25:43.848293139Z] loading plugin "io.containerd.grpc.v1.sandbox-controllers"...  type=io.containerd.grpc.v1
INFO[2023-12-19T10:25:43.848441887Z] loading plugin "io.containerd.grpc.v1.sandboxes"...  type=io.containerd.grpc.v1
INFO[2023-12-19T10:25:43.848463076Z] loading plugin "io.containerd.grpc.v1.snapshots"...  type=io.containerd.grpc.v1
INFO[2023-12-19T10:25:43.848490428Z] loading plugin "io.containerd.grpc.v1.streaming"...  type=io.containerd.grpc.v1
INFO[2023-12-19T10:25:43.848569045Z] loading plugin "io.containerd.grpc.v1.tasks"...  type=io.containerd.grpc.v1
INFO[2023-12-19T10:25:43.848594547Z] loading plugin "io.containerd.grpc.v1.transfer"...  type=io.containerd.grpc.v1
INFO[2023-12-19T10:25:43.848742462Z] loading plugin "io.containerd.grpc.v1.version"...  type=io.containerd.grpc.v1
INFO[2023-12-19T10:25:43.848765822Z] loading plugin "io.containerd.tracing.processor.v1.otlp"...  type=io.containerd.tracing.processor.v1
INFO[2023-12-19T10:25:43.848789341Z] skip loading plugin "io.containerd.tracing.processor.v1.otlp"...  error="no OpenTelemetry endpoint: skip plugin" type=io.containerd.tracing.processor.v1
INFO[2023-12-19T10:25:43.848815341Z] loading plugin "io.containerd.internal.v1.tracing"...  type=io.containerd.internal.v1
INFO[2023-12-19T10:25:43.848829451Z] skipping tracing processor initialization (no tracing plugin)  error="no OpenTelemetry endpoint: skip plugin"
INFO[2023-12-19T10:25:43.849402096Z] serving...                                    address=/var/run/docker/containerd/containerd-debug.sock
INFO[2023-12-19T10:25:43.849843536Z] serving...                                    address=/var/run/docker/containerd/containerd.sock.ttrpc
INFO[2023-12-19T10:25:43.850039914Z] serving...                                    address=/var/run/docker/containerd/containerd.sock
INFO[2023-12-19T10:25:43.850111407Z] containerd successfully booted in 0.054331s
INFO[2023-12-19T10:25:43.892042049Z] Loading containers: start.
INFO[2023-12-19T10:25:43.978291484Z] Loading containers: done.
INFO[2023-12-19T10:25:43.991579126Z] Docker daemon                                 commit=311b9ff graphdriver=overlay2 version=24.0.7
INFO[2023-12-19T10:25:43.992161922Z] Daemon has completed initialization
INFO[2023-12-19T10:25:44.036184473Z] API listen on /var/run/docker.sock
INFO[2023-12-19T10:25:44.036664068Z] API listen on [::]:2376
```

</details>

**Comment by tianon** [comment]
Extremely appreciated, @stevexuereb :bow:
(it's always stressful when we break lots of people at once :sweat_smile:)

File: dockerd-entrypoint.sh (hunk 1 above)
Comment (tianon) [reply dockerd-entrypoint.sh:159]: I found the code in `iptables` itself responsible for that check: :smile:

https://git.netfilter.org/iptables/tree/iptables/nft-shared.c?id=f5cf76626d95d2c491a80288bccc160c53b44e88#n420

It's effectively "read from `/proc/net/ip_tables_names` and if it's non-empty, print the warning", so we can do better than grepping the output of the tool and can instead do a simple `[ -s /proc/net/ip_tables_names ]` (although we probably ought to do all three of those "legacy" files the upstream code references, for good measure).

**Comment by tianon** [comment]
I thought about adding the following as well, but discussing with @ag-TJNII in #466 came up with the idea of an explicit configuration flag for getting legacy instead, since checking loaded modules is _really_ fragile (what if the module was loaded a while ago and never used?  what if one module is built-in in the kernel config, but the other isn't? etc etc etc)

```patch
diff --git a/dockerd-entrypoint.sh b/dockerd-entrypoint.sh
index e610cca..0d3a581 100755
--- a/dockerd-entrypoint.sh
+++ b/dockerd-entrypoint.sh
@@ -156,6 +156,10 @@ if [ "$1" = 'dockerd' ]; then
 		# https://git.netfilter.org/iptables/tree/iptables/nft-shared.c?id=f5cf76626d95d2c491a80288bccc160c53b44e88#n420
 		# if we already have any "legacy" iptables rules, we should always use legacy (https://github.com/docker-library/docker/pull/468#discussion_r1430804593)
 		iptablesLegacy=1
+	elif grep -qE '^ip_tables ' /proc/modules && ! grep -qE '^nf_tables ' /proc/modules; then
+		# if the "ip_tables" module is loaded but the "nf_tables" module is not, we should probably use legacy (to match the host)
+		# in theory, this helps with broken implementations like CentOS 7 which *has* the "nf_tables" module but it appears to not work properly inside a network namespace (https://github.com/docker-library/docker/issues/466)
+		iptablesLegacy=1
 	elif ! iptables -nL > /dev/null 2>&1; then
 		# if iptables fails to run, chances are high the necessary kernel modules aren't loaded (perhaps the host is using xtables, for example)
 		# https://github.com/docker-library/docker/issues/350
```

**Comment by tianon** [comment]
Since the current implementation amounts to effectively "always use legacy" (matching the previous Alpine 3.18 image behavior), I also think it might be prudent at this point in December to wait until the new year to move further on this (in the interest of being respectful to folks' holidays if we _do_ manage to regress again with this).

File: dockerd-entrypoint.sh [hunk 2]
```diff
@@ -143,17 +143,38 @@ if [ "$1" = 'dockerd' ]; then
 	# XXX inject "docker-init" (tini) as pid1 to workaround https://github.com/docker-library/docker/issues/318 (zombie container-shim processes)
 	set -- docker-init -- "$@"
 
-	if ! iptables -nL > /dev/null 2>&1; then
+	iptablesLegacy=
+	if [ -n "${DOCKER_IPTABLES_LEGACY+x}" ]; then
+		# let users choose explicitly to legacy or not to legacy
+		iptablesLegacy="$DOCKER_IPTABLES_LEGACY"
```
Comment (tianon) [inline dockerd-entrypoint.sh:149]: I didn't actually test this before I pushed it, but now I have: :sweat_smile:

```console
$ docker run --rm 3f3f60609d5a |& grep '^iptables '
iptables v1.8.10 (nf_tables)
$ docker run --rm --env DOCKER_IPTABLES_LEGACY= 3f3f60609d5a |& grep '^iptables '
iptables v1.8.10 (nf_tables)
$ docker run --rm --env DOCKER_IPTABLES_LEGACY=1 3f3f60609d5a |& grep '^iptables '
iptables v1.8.10 (legacy)
```

Comment (frederikbosch) [reply dockerd-entrypoint.sh:149]: Giving users the opportunity to decide for themselves is the best option I think.

**Comment by stanhu** [comment]
I repeated @stevexuereb's test with Google COS 105. It works with `--env DOCKER_IPTABLES_LEGACY=1`, but fails without it, as explained in https://github.com/docker-library/docker/issues/467#issuecomment-1868218610.

File: dockerd-entrypoint.sh (hunk 1 above)
Comment (tianon) [reply dockerd-entrypoint.sh:171]: > Oh, interesting! Any idea in what situations/use cases a fresh network namespace might have legacy tables set up in it already?

Did some more testing and figured this out -- it turns out that on CentOS 7, `/proc/net/ip_tables_names` is _not_ empty in a brand new network namespace, even though there aren't any actual rules.  What's even funnier is that I was confused by that upstream code reading from the files and then throwing away everything it reads, but it turns out that's done because these special kernel files have contents, but if you `stat` them their size is 0 bytes. :upside_down_face:

```console
8637e230c491:/# test -s /proc/net/ip_tables_names; echo $?
1
8637e230c491:/# stat /proc/net/ip_tables_names
  File: /proc/net/ip_tables_names
  Size: 0         	Blocks: 0          IO Block: 1024   regular empty file
Device: 29h/41d	Inode: 4026532469  Links: 1
Access: (0440/-r--r-----)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-01-04 18:43:59.112212543 +0000
Modify: 2024-01-04 18:43:59.112212543 +0000
Change: 2024-01-04 18:43:59.112212543 +0000
8637e230c491:/# cat /proc/net/ip_tables_names
nat
mangle
security
raw
filter
```

(so my `-s` test isn't sufficient :disappointed:)

**Comment by tianon** [comment]
I spent a bunch of time today trying to find a way to detect `CONFIG_NF_TABLES` being loaded/built-in on the kernel reliably (ie, even if it's set to `=Y` and thus won't show up in `/proc/modules`), and came up empty handed. :disappointed:

The more I mess with this, the more I'm of the opinion that we should follow the distros/kernel (for example, Debian 10 / Buster is when Debian switched to `nftables`, and Ubuntu was definitely switched in 20.04) and just default to `nftables` with the manual (and temporary!) legacy escape hatch.  At _most_ maybe (correctly) implementing the "if legacy rules seem to exist, use legacy" (https://github.com/docker-library/docker/pull/468#discussion_r1431778320), since that's a strong signal that we should use legacy.

What I _don't_ want to do is give the appearance that anything but `nftables` is actually well-supported, because we don't really know (or have any control over) how long "legacy" will still be available/usable/possible for us to support (the legacy wrappers being removed entirely from Alpine, for example).

**Comment by tianon** [comment]
With this latest push, I successfully get `iptables v1.8.10 (legacy)` on CentOS 7 (even with `nf_tables` loaded and supposedly working) and `iptables v1.8.10 (nf_tables)` on my Debian host.

**Comment by tianon** [comment]
Anyone feel like testing this one more time before we merge? :eyes: (ie, last call! :sweat_smile:)

**Comment by stanhu** [comment]
Tested the latest changes with Google Container OS:

* COS 85: ✅
* COS 105 needs `--env DOCKER_IPTABLES_LEGACY=1`, but otherwise ✅

**Comment by tianon** [comment]
Thanks @stanhu!!  It's really appreciated :bow:

**Comment by Chickenmarkus** [comment]
> Tested the latest changes with Google Container OS: 
>     * COS 85: ✅
>     * COS 105 needs `--env DOCKER_IPTABLES_LEGACY=1`, but otherwise ✅

Some more background information for documentation only because the internet search leads to this issue.

It is not an issue with COS 105 in general but with [build ID 17412.226.68](https://cloud.google.com/container-optimized-os/docs/release-notes/m105#cos-105-17412-226-68_) and below. It already includes the kernel module `nf_tables` which is detected and used by the docker startup scripts. However, this kernel module is not functional yet and, thus, the startup scripts fail.
With build ID [17412.294.10](https://cloud.google.com/container-optimized-os/docs/release-notes/m105#cos-105-17412-294-10_) first, the kernel module `nf_tables` has officially been announced and is functional.

As a result, our GKE 1.26.6-gke.1700 (uses [cos-101-17162-210-48](https://cloud.google.com/container-optimized-os/docs/release-notes/m101#July_05_2023)) was working before the automatic update in the REGULAR release channel but was not after the upgrade to 1.27.8-gke.1067004 (uses [cos-105-17412-226-62](https://cloud.google.com/container-optimized-os/docs/release-notes/m105#January_02_2024)).
We had to manually upgrade to the RAPID release channel (1.29.1-gke.1589017 with [cos-109-17800-66-78](https://cloud.google.com/container-optimized-os/docs/release-notes/m109#cos-109-17800-66-78_)) or pin the version to 1.27.11-gke.1062000 (uses [cos-105-17412-294-29](https://cloud.google.com/container-optimized-os/docs/release-notes/m105#cos-105-17412-294-29_)).

File: dockerd-entrypoint.sh [hunk 3]
```diff
@@ -143,17 +143,46 @@ if [ "$1" = 'dockerd' ]; then
...
+		if [ -n "$iptablesLegacy" ]; then
+			modprobe ip_tables || :
+		else
+			modprobe nf_tables || :
+		fi
+	elif (
+		# https://git.netfilter.org/iptables/tree/iptables/nft-shared.c?id=f5cf76626d95d2c491a80288bccc160c53b44e88#n420
+		# https://github.com/docker-library/docker/pull/468#discussion_r1442131459
+		for f in /proc/net/ip_tables_names /proc/net/ip6_tables_names /proc/net/arp_tables_names; do
```
Comment (erichorwath) [inline dockerd-entrypoint.sh:158]: @tianon what is the reason the dependency to the `arp_tables` module has been introduced?

What is the impact on dind (on K8s), when the K8s node does not have `arp_tables` loaded?
(tested with latest `docker:dind`)
image
